suppressMessages({library(caret); library(dplyr); library(reshape2); library(fitdistrplus)})
source('r11.R'); source('r13.R'); source('r12.R')
sink('/dev/null')   # silencia os prints das funções originais
cls <- c('F','VS','PA','SE')
g  <- read.csv('gauss.csv'); ga <- read.csv('gamma.csv'); pr <- read.csv('pair.csv')
out <- list()
# --- 11: separabilidade
out$B_gauss <- as.matrix(bhattacharyya_distance_matrix(g, cls))
out$B_gamma <- as.matrix(bhattacharyya_distance_matrix(ga, cls, 'gamma', L = 3))
out$JM      <- as.matrix(jeffryes_matusita_distance_matrix(g, cls))
out$meanJM  <- mean_jm_distance(g, cls)
fs <- exhaustive_search_jm_optimal(g, cls, c('B1','B2','B3'))
write.csv(fs[[1]], 'R_fs_dist.csv', row.names = FALSE); write.csv(fs[[2]], 'R_fs_res.csv', row.names = FALSE)
hc <- hclust(as.dist(out$B_gauss), method = 'ward.D2')
h  <- extract_hierarchy(hc)
writeLines(sapply(h, function(x) paste(sort(x), collapse = '+')), 'R_hier.txt')
write.csv(hc$height, 'R_heights.csv', row.names = FALSE)
for (n in c('B_gauss','B_gamma','JM')) write.csv(out[[n]], paste0('R_', n, '.csv'))
write.csv(out$meanJM, 'R_meanJM.csv', row.names = FALSE)
# --- 11: verossimilhanças
tr <- read.csv('gauss_train.csv'); te <- read.csv('gauss_test.csv')
p <- parameters_estimation(tr, cls); lk <- gaussian_class_likelihood(te[, -1], p)
write.csv(lk, 'R_lik_gauss.csv', row.names = FALSE)
tr <- read.csv('gamma_train.csv'); te <- read.csv('gamma_test.csv')
p <- parameters_estimation(tr, cls, 'gamma', ENL = 3); lk <- gamma_class_likelihood(te[, -1, drop = FALSE], p)
write.csv(lk, 'R_lik_gamma.csv', row.names = FALSE)
cls3 <- c('F','PA','SE')
tr <- read.csv('pair_train.csv'); te <- read.csv('pair_test.csv')
p <- parameters_estimation(tr, cls3, 'intensity_joint_distribution')
write.csv(do.call(rbind, lapply(p, unlist)), 'R_par_pair.csv', row.names = FALSE)
lk <- intensity_joint_likelihood(te[, -1], p, 4)
write.csv(lk, 'R_lik_pair.csv', row.names = FALSE)
# --- 11/13: agregação e métricas
cm <- as.matrix(read.csv('cm.csv', row.names = 1))
dimnames(cm) <- list(Prediction = rownames(cm), Reference = colnames(cm))
ag <- aggregate_classes(cm, c('F','VS')); write.csv(as.data.frame.matrix(ag), 'R_agg.csv')
m <- metrics_calculation(cm)
write.csv(data.frame(OA = m$overall_accuracy, F1M = m$f1_macro), 'R_metrics_global.csv', row.names = FALSE)
write.csv(data.frame(PA = m$producers_accuracy, UA = m$users_accuracy, F1 = m$f1_score), 'R_metrics_class.csv')
# --- 13: uma iteração determinística para cada modelo
one_iter <- function(name, classes, pf, ENL) {
  tr <- read.csv(paste0(name, '_train.csv')); te <- read.csv(paste0(name, '_test.csv'))
  p  <- parameters_estimation(tr, classes, pf, ENL)
  vp <- te[sapply(te, is.numeric)]
  lk <- if (pf == 'gamma') gamma_class_likelihood(vp, p) else if (pf == 'intensity_joint_distribution') intensity_joint_likelihood(vp, p, ENL) else gaussian_class_likelihood(vp, p)
  pc <- maximum_likelihood_classifier(lk)
  df <- match_classes(pc, te, classes)
  cmx <- confusion_matrix_table(df)
  write.csv(df, paste0('R_pred_', name, '.csv'), row.names = FALSE)
  write.csv(cmx, paste0('R_cm_', name, '.csv'))
}
one_iter('gauss', cls, 'gaussian', NULL); one_iter('gamma', cls, 'gamma', 3); one_iter('pair', cls3, 'intensity_joint_distribution', 4)
# --- 12: ajustes
gf <- gamma_fitting(ga, cls); write.csv(gf, 'R_gfit.csv', row.names = FALSE)
gm <- gamma_fitting(ga, cls, method = 'mme'); write.csv(gm, 'R_gfit_mme.csv', row.names = FALSE)
gs <- gamma_fitting_specific(ga, cls, 3); write.csv(gs, 'R_gspec.csv', row.names = FALSE)
it <- iterative_gamma_fitting(ga, cls); write.csv(it$Result_counting, 'R_iter.csv', row.names = FALSE)
write.csv(it$Best_ENL, 'R_bestenl.csv', row.names = FALSE)
gn <- normal_fitting(g[, c('Class','B1')], cls); write.csv(gn, 'R_nfit.csv', row.names = FALSE)
sink()
cat('R ok\n')
